use moni;
select * from productsb;
-- Product Analysis
-- 1. How many product category are there ?
select 
product_category
from productsb
group by product_category;
-- 2. Which product has highest unit price ?
select
 product_category,
max(unit_price)
from productsb
group by product_category;
-- 3. How many quantity are sold in each product_category ?
select 
product_category,
count(quantity_sold)
from productsb
group by product_category;
-- 4. What is the total sales of each product ?
select 
product_category,
sum(quantity_sold * unit_price) as Revenue
from productsb
group by product_category
order by Revenue desc;
-- 5. What is the minimum of total sales?
select
product_category,
min(quantity_sold*Unit_price) as Total_Sales
from productsb
group by product_category
order by total_sales desc;
-- 6. which sales_rep is highest quantity_sold?
select
sales_rep,
sum(quantity_sold)
from productsb
group by sales_rep;
-- 7. which region is most pruchsed products and their sales_rep ?
select
product_category,
region_and_sales_rep,
sum(quantity_sold) over (partition by product_category,
region_and_sales_rep
order by quantity_sold asc) as total_quantity
from productsb;
-- 8. which product has the average total sales value?
select product_category,
avg(quantity_sold * unit_price) over (partition by product_category
order by quantity_sold desc) as Total_sales
from productsb;
--  9. which product has the average total sales value?
select product_category,
avg(quantity_sold*unit_price) as Total_sales
from productsb
group by product_category;
-- 10. Which customer_type is most purchased by the customers:
select 
product_category,
customer_type,
sum(quantity_sold) 
from productsb
group by product_category,customer_type;
-- 11. What is the total revenue generated by each region?
select
Region,
sum(quantity_sold*unit_price) as Total_Revenue
from productsb
group by region;
-- 12. Which sales_channel highly used by the customers?
select sales_channel,
sum(quantity_sold)
from productsb
group by sales_channel;
-- 13. Which products should be promoted to increase revenue?
select
 ï»¿Product_ID,
 product_category,
 sum(quantity_sold*unit_price) as Total_Revenue
 from productsb
 group by ï»¿Product_ID,product_category
 order by total_Revenue desc;
 -- 14. What is the average price of products in each category?
 select 
 product_category,
 avg(unit_price)
 from productsb
 group by product_category;
 -- 15. What is the total sales in each sales_rep?
 select 
 sales_rep,
 sum(quantity_sold*unit_price) as Total_sales
 from productsb
 group by sales_rep
 order by Total_sales desc;
 -- 16. Which sales rep is most use in online sales channel?
 select
 sales_rep,
 sales_channel,
 max(quantity_sold*unit_price) as Total_sales
 from productsb
 where sales_channel="online"
 group by sales_rep
 order by Total_sales desc;
-- 17. Which sales rep is maximum use in retail sales channel?
 select
 sales_rep,
 sales_channel,
 max(quantity_sold*unit_price) as Total_sales
 from productsb
 where sales_channel="retail"
 group by sales_rep
 order by Total_sales desc;
 -- 18. which product_id is highest total sales?
 select
 ï»¿Product_ID,
 sum(quantity_sold*unit_price) as Total_sales
 from productsb
 group by ï»¿Product_ID
 order by Total_sales desc;
 -- 19.  Which product is get the highest discount?
 select 
 product_category,
 sum(discount)
 from productsb
 group by product_category;
 -- 20. Which product is get the most frequently orders?
 select
ï»¿Product_ID,
product_category,
count(quantity_sold) as Total_quantity
from productsb
group by ï»¿Product_ID,product_category
order by Total_quantity desc;
 
 




















